plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'io.freefair.lombok' version '9.2.0'
}

repositories { mavenCentral() }

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = "MazeGame"
}

dependencies {
    testImplementation 'junit:junit:4.12'
    compileOnly "org.projectlombok:lombok:1.18.42"
    annotationProcessor "org.projectlombok:lombok:1.18.42"
}

javafx {
    version = "25.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
